name = "DefaultApplication"
uuid = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.3"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
