name = "DefaultApplication"
uuid = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.5"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
